sudo: false
language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run coverage
  - npm run bundle
deploy:
  on:
      branch: master
  provider: npm
  email: CalebLemoine@gmail.com
  api_key: $npmToken